### ISSUE TITLE
Custom css

### ISSUE THREAD

**Issue by DiarQoroviqi** [shopwareLabs/SwagLightweightModule#7]
Is it possible to add custom css file on css folder and then include it to the main layout?

**Comment by mitelg** [comment]
hey @DiarQoroviqi 

have a look here: https://github.com/shopwareLabs/SwagLightweightModule/blob/master/Resources/views/backend/_base/layout.tpl#L6
we load a custom.css here, which is located here: https://github.com/shopwareLabs/SwagLightweightModule/tree/master/Resources/views/backend/_resources/css

**Comment by DiarQoroviqi** [comment]
I did it in the same way but for some reasons it doesn't work? Do I have to add any extra config or something else?

**Comment by mitelg** [comment]
not that I know of :thinking: 

to be honest this is a plugin, we haven't maintained in a while. and I don't know if it is even working anymore :see_no_evil:

**Comment by teiling88** [comment]
@mitelg it is working with Shopware 5.6.10 :-) I used it some weeks ago as a basic for a new Plugin :-)
